import { createContext } from "react";
import {
  Action,
  Payload,
  ProtoSlice,
  Slice,
  StoreBranchWithDispatch,
} from "../types";

/**
 * Creates a reducer function out of the store slice reducers. The reducers work
 * as an object literal switch
 */

export const reducer =
  <T extends string, R>(reducers: Slice<T, R>["reducers"]) =>
  (currentState: R, { type, payload }: Action<T>): R =>
    reducers[type] ? reducers[type](currentState, payload) : currentState;

/**
 * Adds a _reducer_ attribute to the store slice. It's a function as the one in
 * the following example:
 *
 * @example
 *   const reducerFunctionExample = (
 *     currentState: R,
 *     { type, payload }: Action<T>
 *   ) => R;
 */

export const SetReducer = <T extends string, R>(
  methods: ProtoSlice<T, R>["reducers"]
): Pick<Slice<T, R>, "reducer"> => ({
  reducer: reducer(methods),
});

/**
 * Adds a _Context_ attribute to the store slice. It contains the context
 * generated by the React createContext function
 */

export const SetContext = <T extends string, R>(slice: ProtoSlice<T, R>) => ({
  Context: createContext<StoreBranchWithDispatch<R, T>>({
    [slice.name]: slice.initialState,
    dispatch: () => {},
  }),
});

/**
 * Adds a _actions_ attribute to the store slice. It contains all the actions
 * creators, generated automatically from the slice reducers.
 *
 * The action creators are curried, to make possible a global declaration with
 * typing
 */

export const SetActions = <T extends string, R>(
  reducers: ProtoSlice<T, R>["reducers"]
) => ({
  actions: Object.keys(reducers).reduce((actions, name) => {
    return {
      ...actions,
      [name]: () => (payload?: Payload) => {
        const action = {
          type: name as T,
        };

        return payload ? { ...action, payload } : action;
      },
    };
  }, {}) as Slice<T, R>["actions"],
});

/**
 * @param slice A slice with only its name, initial value and methods
 * @returns A full slice with the proto slice attributes and also a reducer
 *   function and its react context
 */

export const createSlice = <T extends string, R>(
  slice: ProtoSlice<T, R>
): Slice<T, R> => ({
  ...slice,
  ...SetContext(slice),
  ...SetReducer(slice.reducers),
  ...SetActions(slice.reducers),
});

export default createSlice;
